spring:
  application:
    name: spring-security-custom-authn

  datasource:
    url: jdbc:postgresql://localhost:5436/security_test_db
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop