spring:
  application:
    name: spring-security-custom-authn

  datasource:
    url: jdbc:postgresql://localhost:5436/security_test_db
    username: postgres
    password: password

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always

logging:
  level:
    org.springframework.security: DEBUG

app:
  security:
    jwt:
      key-id: local-dev-key-1
      issuer: test-security-app
      access-token-expiration: 300000
      private-key: ${JWT_PRIVATE_KEY_PATH:classpath:secrets/private.pem}
      public-key: ${JWT_PUBLIC_KEY_PATH:classpath:secrets/public.pem}
      audience:
        - test-security-app