spring:
  application:
    name: spring-security-custom-authn

  datasource:
    url: jdbc:postgresql://localhost:5436/security_test_db
    username: postgres
    password: password

  sql:
    init:
      mode: always
      data-locations: classpath:sql/data.sql
      schema-locations: classpath:sql/schema.sql

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

logging:
  level:
    org.springframework.security: DEBUG